### ISSUE TITLE
Пошли играть, заебал 

### ISSUE THREAD

**Issue by Delinser** [aleksdupx/Game1#1]
Играть пошли, заебал

**Comment by aleksdupx** [comment]
Пошел нахуй

**Comment by aleksdupx** [comment]
Мне блять пришлось пароль восстанавливать от гитхаба, чтобы тебя нахуй послать.

**Comment by aleksdupx** [comment]
https://youtu.be/kHu1dIFRUO4

**Comment by Delinser** [comment]
Ну пошли, заебал

**Comment by Delinser** [comment]
Идет суд. Судья: 
— Свидетель Георгадзе! 
Тишина...
— Свидетель Георгадзе! 
Встает грузин. 
Судья: 
— Ну расскажите как все было, что вы видели? 
— Ничего я нэ видэл...
— Вы свидетель Георгадзе? 
— Нэт 
— А почему встали? 
— Сэйчас жопу почешу и сяду
