### ISSUE TITLE
Ну заебал, пошли 

### ISSUE THREAD

**Issue by Delinser** [aleksdupx/Game1#2]

**Comment by aleksdupx** [comment]
Если еще не понял перейди по ссылке https://youtu.be/kHu1dIFRUO4. 
Если даже после просмотра не понял, еще раз зайди по ссылке и посмотри.

**Comment by aleksdupx** [comment]
И так пока не поймешь. А если вообще туго, то запишись в поликлинику, там тебе помогут понять.
